name: Build pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pages: write

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build site
        run: mdbook build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./docs/book/

  deploy:
    needs: build
    runs-on: "ubuntu-22.04"

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
